[package]
name = "lexer"
version = "0.1.0"
authors = ["Francesco Ruta <francescoruta.99@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
once_cell = "1.8"
regex = "1"
shared = { path = "../shared" }