[package]
name = "macros"
version = "0.1.0"
authors = ["Francesco Ruta <francescoruta.99@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.1.0"
syn = { version = "1", features = ["extra-traits", "full"] }
quote = "1"